import { MarkerType } from '@xyflow/react';

export const nodes = [
  {
    id: 'antennar-cloud',
    type: 'default',
    position: { x: 400, y: 50 },
    data: { label: 'Antennar Cloud' },
    style: {
      backgroundColor: '#1a1a1a',
      color: 'white',
      border: '2px solid #333',
      borderRadius: '25px',
      width: 180,
      height: 60,
    },
  },
  {
    id: 'tx-node-002',
    type: 'default',
    position: { x: 50, y: 200 },
    data: { label: 'TX Node 002' },
    style: {
      backgroundColor: '#dcfce7',
      border: '2px solid #16a34a',
      borderRadius: '8px',
      width: 140,
      height: 50,
    },
  },
  {
    id: 'rx-node-002',
    type: 'default',
    position: { x: 650, y: 200 },
    data: { label: 'RX Node 002' },
    style: {
      backgroundColor: '#dbeafe',
      border: '2px solid #2563eb',
      borderRadius: '8px',
      width: 140,
      height: 50,
    },
  },
  {
    id: 'edge-server-b',
    type: 'default',
    position: { x: 550, y: 150 },
    data: { label: 'Edge Server B' },
    style: {
      backgroundColor: '#fef3c7',
      border: '2px solid #f59e0b',
      borderRadius: '8px',
      width: 120,
      height: 45,
    },
  },
  {
    id: 'iot-cluster',
    type: 'default',
    position: { x: 200, y: 320 },
    data: { label: 'IoT Cluster' },
    style: {
      backgroundColor: '#f3f4f6',
      border: '2px solid #6b7280',
      borderRadius: '8px',
      width: 110,
      height: 45,
    },
  },
  {
    id: '5g-base-station',
    type: 'default',
    position: { x: 600, y: 320 },
    data: { label: '5G Base Station' },
    style: {
      backgroundColor: '#f3f4f6',
      border: '2px solid #6b7280',
      borderRadius: '8px',
      width: 140,
      height: 45,
    },
  },
];

export const edges = [
  {
    id: 'e1',
    source: 'antennar-cloud',
    target: 'tx-node-002',
    label: 'Vision Feed',
    style: { stroke: '#16a34a', strokeWidth: 2 },
    type: 'smoothstep',
  },
  {
    id: 'e2',
    source: 'antennar-cloud',
    target: 'edge-server-b',
    label: 'Data Stream',
    style: { stroke: '#2563eb', strokeWidth: 2 },
    type: 'smoothstep',
  },
  {
    id: 'e3',
    source: 'edge-server-b',
    target: 'rx-node-002',
    label: 'Direct Link',
    style: { stroke: '#f59e0b', strokeWidth: 2 },
    type: 'smoothstep',
  },
  {
    id: 'e4',
    source: 'rx-node-002',
    target: '5g-base-station',
    label: 'mmWave Link',
    style: { stroke: '#6b7280', strokeWidth: 2, strokeDasharray: '5,5' },
    type: 'smoothstep',
  },
  {
    id: 'e5',
    source: 'antennar-cloud',
    target: 'iot-cluster',
    label: 'Signal Route',
    style: { stroke: '#8b5cf6', strokeWidth: 2 },
    type: 'smoothstep',
  },
  {
    id: 'e6',
    source: 'edge-server-b',
    target: '5g-base-station',
    label: '5G Backhaul',
    style: { stroke: '#f59e0b', strokeWidth: 2 },
    type: 'smoothstep',
  },
];